Phase2
ivahei/ToDo pull request #2
Opened 2021-12-10 20:09 UTC by ivahei

Barev Hovak jan,, tcragris en xndir@ full chtsacvec lucel VCn verakangneci bayc eli kesic sevanum  a,, esor kporcem arag es project@ verjacnem ugharkem.

2021-12-10 23:15 UTC, hovaks approved these changes

2021-12-10 23:15 UTC, hovaks commented on ToDo/Controller/ToDoTableViewController.swift
> +        if let savedToDos = ToDo.loadToDos() {
կարելի էր նաև գրել սենց todos = ToDo.loadToDos() ?? ToDo.loadSampleToDos()
գիտեմ, որ գրքում տենց ա գրած բայց պարտադիր չի էլի նույն ձև գրել

2021-12-10 23:15 UTC, hovaks commented on ToDo/Controller/ToDoTableViewController.swift
> +            todos = ToDo.loadSumpleToDos()
Հիշացրու ցույց տամ՝ ոնց անես, որ տառասխալներդ ընդգծի

2021-12-10 23:15 UTC, hovaks commented on ToDo/Controller/ToDoTableViewController.swift
> +        // #warning Incomplete implementation, return the number of rows
էս արժեր ջնջել

2021-12-10 23:15 UTC, hovaks commented on ToDo/Controller/ToDoTableViewController.swift
> +    // Override to support conditional editing of the table view.
սրանք էլ արժեր ջնջել

2021-12-10 23:15 UTC, hovaks commented on ToDo/Model/ToDoModel.swift
> +
անկապ ծակ ա

2021-12-10 23:17 UTC, hovaks requested changes
էս քոմենթները դզի էլի, նոր շարժվենք առաջ, համ էլ հետաքրքիր դեպքեր կարան առաջանան

2021-12-10 23:27 UTC, ivahei commented
Ha dranq sagh hajordum dzel em chei nkatel

On Sat, 11 Dec 2021 at 03:17 hovaks ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> էս քոմենթները դզի էլի, նոր շարժվենք առաջ, համ էլ հետաքրքիր դեպքեր կարան
> առաջանան
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ivahei/ToDo/pull/2#pullrequestreview-829401855>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALI3BS2HEU75XUXYHZ3XZKLUQKC7VANCNFSM5JZ54WIQ>
> .
>

2021-12-10 23:30 UTC, hovaks commented
> Ha dranq sagh hajordum dzel em chei nkatel
> […](#)

Կարամ մերջեմ էլ, բայց ավելի լավ կլինի էս փոփոխությունները անես էս բրենչի վրա, որից փիառ ես բացել, տենց մերջենք, հետո մնացած կոդիդ հետ էլ երևի կոնֆլիկտ կտա, կակռազ սովորենք էդ վախտ ինչ ա պետք անել

2021-12-11 11:24 UTC, hovaks approved these changes

2021-12-11 11:24 UTC, merged